### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by Gorialis** [darthshittious/darthshittious#1]
I can see you've duplicated a bunch of content from my README repository, including the autogeneration code verbatim. I don't usually care about these things (I wouldn't license things permissively otherwise), but I will refer you to this clause of the license:

> Permission is hereby granted, free of charge, to any person obtaining a copy
> of this software and associated documentation files (the "Software"), to deal
> in the Software without restriction, including without limitation the rights
> to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
> copies of the Software, and to permit persons to whom the Software is
> furnished to do so, **subject to the following conditions**:
>
> **The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.**

You must reproduce my copyright on your repository for it to be a valid usage of the license. My repository has signed commits and action workflows proving their origin and timestamp, so if you don't want to add the license or copyright clause voluntarily, I will gladly have GitHub remove the repository instead.

**Comment by darthshittious** [comment]
Sincerest apologies. This was from a time when I didn't care about/understand licensing. Attributions have been added now.
Thank you for bringing this to my notice.
